### ISSUE TITLE
Error starting face scan on Metamap Flutter

### ISSUE THREAD

**Issue by MrNyamu** [GetMetaMap/metamap-flutter-plugin#25]
Hello Metamap team, I am having an issue with the metamap flutter SDK on the android build where a user is not able to initiate the face scan. The Metamap flow crashes immediately when navigating to that process. Kindly assist

**Comment by MrNyamu** [comment]
https://user-images.githubusercontent.com/108067565/204224766-0e9e5f6b-5745-4471-855b-3ea464a7cda6.MOV

Here is a video showing the flow.

**Comment by AvoSukiasyan** [comment]
hello @MrNyamu. sorry for the late answer. 
can you clarify? please. what SDK version do you use?

**Comment by MrNyamu** [comment]
Hey there, I resolved this issue already, It was an update on the camera work dependancy that was needed that fixed the issue. Thank you for attempting to assist.
