### ISSUE TITLE
Codemagic - Unexpected ',' separator

### ISSUE THREAD

**Issue by Pashi98** [GetMetaMap/metamap-flutter-plugin#27]
I'm having this error when trying to build ios with Codemagic:

> Xcode archive done.                                         19.9s
> Failed to build iOS app
> Swift Compiler Error (Xcode): Unexpected ',' separator
> /Users/builder/.pub-cache/hosted/pub.dev/metamap_plugin_flutter-4.1.2/ios/Classes/SwiftMetaMapPluginFlutterPlugin.swift:31:55
> 
> Encountered error while archiving for device.
> 
> 
> Build failed :|
> Failed to build for iOS

As said in the error, there is an "extra" comma in the ios/Classes/SwiftMetaMapPluginFlutterPlugin.swift and build fails.

**Comment by AvoSukiasyan** [comment]
hi @Pashi98 . let me check it and I get back to you

**Comment by nestorsgarzonc** [comment]
Hi, the error is this trailing comma:
<img width="843" alt="image" src="https://github.com/GetMetaMap/metamap-flutter-plugin/assets/40438456/8aa0ec77-d324-486e-b71f-ae8072a5ab71">

**Comment by nestorsgarzonc** [comment]
You solve this:
<img width="599" alt="image" src="https://github.com/GetMetaMap/metamap-flutter-plugin/assets/40438456/7349ec32-74c2-4a64-86f5-600c2af71244">

**Comment by AvoSukiasyan** [comment]
HI @nestorsgarzonc. the problem is fixed
