### ISSUE TITLE
[Android] Namespace

### ISSUE THREAD

**Issue by danedyy** [GetMetaMap/metamap-flutter-plugin#28]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':metamap_plugin_flutter'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by AvoSukiasyan** [comment]
hi @danedyy . can you check the last (4.1.5) version, please ?
