### ISSUE TITLE
Error compiling in iOS

### ISSUE THREAD

**Issue by nestorsgarzonc** [GetMetaMap/metamap-flutter-plugin#29]
Hi, I'm using the last version of the plugin `metamap_plugin_flutter: ^4.2.0` but I get the following error:

```
Swift Compiler Error (Xcode): No such module 'Sentry'
/Users/X/Desktop/app/build/ios/Debug-X-iphonesimulator/XCFrameworkIntermediates/MetaMapSDK/MetaMapSDK.framework/Modules/MetaMapSDK.swiftmodule/x86_64-apple-ios-simulator.private.swiftinterface:25:7

Swift Compiler Error (Xcode): Failed to build module 'MetaMapSDK' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug
/Users/X/.pub-cache/hosted/pub.dev/metamap_plugin_flutter-4.2.0/ios/Classes/SwiftMetaMapPluginFlutterPlugin.swift:2:7
```

How I can solve it? I'm using the last version of flutter and xcode.

**Comment by codeflames** [comment]
same issue here.

**Comment by AvoSukiasyan** [comment]
please use [4.1.9](https://pub.dev/packages/metamap_plugin_flutter/versions/4.1.9 ) stable version until we'll fix the issue.

**Comment by codeflames** [comment]
Versions [4.1.8](https://pub.dev/packages/metamap_plugin_flutter/versions/4.1.8) and the latest [4.2.8](https://pub.dev/packages/metamap_plugin_flutter/versions/4.2.8) for me. Thank you @AvoSukiasyan .

**Comment by AvoSukiasyan** [comment]
hi @nestorsgarzonc . i know about it. working on it . minimum support version needs to be 12. will fix the issue related to Sentry as soon as possible and inform you

**Comment by AvoSukiasyan** [comment]
I fixed the issue. next week we have release and this fix will be incluede 
cc: @nestorsgarzonc @codeflames

**Comment by nestorsgarzonc** [comment]
@AvoSukiasyan do you have any update about the fix?
