### ISSUE TITLE
A problem occurred evaluating project ':metamap_plugin_flutter'.

### ISSUE THREAD

**Issue by jtavio** [GetMetaMap/metamap-flutter-plugin#33]
Where:
Build file '/Users/gregspinetti/.pub-cache/hosted/pub.dev/metamap_plugin_flutter-4.3.2/android/build.gradle' line: 37

* What went wrong:
A problem occurred evaluating project ':metamap_plugin_flutter'.
> Could not get unknown property 'kotlin_version' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
Launching lib/main_development.dart on Redmi 8 in debug mode...

FAILURE: Build failed with an exception.

> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Error: Gradle task assembleDebug failed with exit code 1

Flutter doctor 
[✓] Flutter (Channel stable, 3.19.6, on macOS 13.6 22G120 darwin-arm64, locale en-VE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources

When adapting the changes to be made in gradle for the new version of flutter 3.16, it starts to give compiling problems.

**Comment by AvoSukiasyan** [comment]
HI @jtavio.  let me check it and get back to you soon

**Comment by Samleet** [comment]
@AvoSukiasyan is there a fix for this yet. i'm still experiencing this issue `"Could not get unknown property 'kotlin_version' for object of type"`

**Comment by AvoSukiasyan90** [comment]
@Samleet @jtavio I'll fix it in the next few days and get back to you

**Comment by Samleet** [comment]
@AvoSukiasyan @jtavio I already made a fix for this issue addressing the namespace declaration and JDK compatibility. should I go ahead and raise a PR?

**Comment by AvoSukiasyan** [comment]
@Samleet yes, please

**Comment by AvoSukiasyan** [comment]
@Samleet can you open MR, please? it's available

**Comment by Samleet** [comment]
@AvoSukiasyan i am unable to create a PR as well

![snap-pr](https://github.com/GetMetaMap/metamap-flutter-plugin/assets/32910421/e9c37322-4b00-4d23-9421-b9db8f9a7431)

**Comment by AvoSukiasyan** [comment]
@Samleet can you share code here, please? 
I'll look it as soon as possible
